### ISSUE TITLE
Feature Request: ZDataStyle with rules to `border-radius` and `gap`

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#10]
Would be nice to have this rules on the `z-data.min.all.js`
something like:
<details>
  <summary>Border Radius</summary>

`brad8px` => 
```
[brad8px=""] {
    border-radius: 8px;
}
``` 
`brad-tl-8px` => 
```
[brad-tl-8px=""] {
    border-top-left-radius: 8px;
}
``` 
`brad-b-8px` => 
```
[brad-b-8px=""] {
    border-bottom-left-radius: 8px;
    border-bottom-right-radius: 8px;
}
``` 
`brad--size` => 
```
[brad--size=""] {
    border-radius: var(--size);
}
```

</details>

<details>
  <summary>Gap</summary>

`gap8px` => 
```
[gap8px=""] {
    gap: 8px;
}
``` 
`gap--gap` => 
```
[gap--size=""] {
    gap: var(--size);
}
``` 
`gap-r-8px` => 
```
[gap-r-8px=""] {
    row-gap: 8px;
}
``` 
`gap-c-8px` => 
```
[gap-c-8px=""] {
    column-gap: 8px;
}
``` 

</details>

**Comment by Funlang** [comment]
Please refer to issue #11 and try to modify it to fit this feature. If you have any troubles, please feel free to contact me.

**Comment by Funlang** [comment]
@jaronwanderley v1.9.9 has been released for this feature.
You could take a look at the /css folder to read more.
BTW, you could debug the code at the online z-data studio http://funlang.org/z-data/. For attr css feature, hover the html css attr you could find the generated css in the top status tips.
