### ISSUE TITLE
Some bug on end of Web Animations API (WAAPI)

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#2]
Hi @Funlang I'm very impressed how lightweight is this framework, until now I was using the Petite Vue for the same proposite, because I needed something very small, and when I saw your framework my eyes shiny again. Soo thank u for your work on this.

I started to migrate my custom elements on Petite Vue to Z-data and I found kind of a bug on rendering the state of the element at the end of an animation. to examplify this I created the same thing in Petite Vue and Z-data.

To reproduce the bug you need to shrink the accordion, and at end of animation will show a jump.

`Animated details summary` on [Petite Vue](https://codepen.io/JaronWanderley/pen/JjvZygM?editors=1000)
`Animated details summary`on [Z-data](https://codepen.io/JaronWanderley/pen/WNJKQBJ?editors=1000)

At the end of animation the state need to be `open === false`, but somehow that was `true ` and I can't figure out how.
Can you help me with this?

**Comment by Funlang** [comment]
Thanks for your example, I will do something to locate the issue.

**Comment by Funlang** [comment]
I don't know how and why.
Changed this line and it works fine.
```javascript
if (start > end) this.open = details.open = false;
```
[https://codepen.io/funlang/pen/zYjmYxE?editors=1010](url)

**Comment by jaronwanderley** [comment]
@Funlang That's work, thak u!!!
> ```js
> if (start > end) this.open = details.open = false;
> ```
but I did it this way, because of the State Based paradigm. So I assumed the `open` state would be more important than touching the property of the Element directly.

but thank u again. I'm closing this issue now.
