### ISSUE TITLE
Feature Request: a way to hide before Z-data initiation

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#3]
I was reading the docs, and I can't find a way to hide some tags before Z-data initiation, like Vue does using `v-cloak`. A example of a code to use:

`[...document.querySelectorAll('[z-cloak]')].map(el => el.removeAttribute('z-cloak'))`

the benefit of using this is that we can do whatever we want with CSS using the selector:

`[z-cloak] { ... }`

**Comment by Funlang** [comment]
```html
<div z-data>
...

<div z-cloak :z-cloak.attr=false>z-cloak example</div>

<style>
  [z-cloak] {
    display: none;
  }
</style>

...
</div>
```

**Comment by jaronwanderley** [comment]
@Funlang thank u!!!
that's the thing I was looking for!
I'm closing this issue now!
