### ISSUE TITLE
Can I use Z-data with SVG?

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#4]
Hi @Funlang I'm here again, but this time I was trying to port another component in Petite Vue to Z-data and had some issues.
First: I can't make the `binding `work with any properties inside elements in `SVG`, like `viewBox`, `x`, `y`, `width`, `height`...
Second: I can't work with `templates ` inside a g tag, I was trying to use `for`

To reproduce the bug I made some examples:

`Graph Bar` on [Petite Vue](https://codepen.io/JaronWanderley/pen/OJZqMXY)
`Graph Bar`on [Z-data](https://codepen.io/JaronWanderley/pen/MWGxegL)

Can you help me with this?

**Comment by Funlang** [comment]
- [x] attributes binding

1. Please use .attr to specify binding to the attribute of Elements (default binding to prop)
1. Demo: https://codepen.io/funlang/pen/LYmaQOw?editors=1000

- [x] templates

1. v1.9.1 released to support template in svg
2. Demo: https://codepen.io/funlang/pen/LYmaQOw?editors=1000

**Comment by Funlang** [comment]
- [x] Z-Data will add a new syntax sugar to bind to attribute. @jaronwanderley 

1. v1.9.2
   + syntax sugar to .attr
    :!tag-attr  -> :tag-attr.attr
    ::!tag-attr -> ::tag-attr.attr

2. Demo: https://codepen.io/funlang/pen/wvjORrV?editors=1000

**Comment by jaronwanderley** [comment]
Thanks man, I'm closing the issue now.
