### ISSUE TITLE
Custom Directive

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#5]
Hi @Funlang I'm here again, I was trying to port some of my custom directives made in Petite Vue, to use with Z-data, but I didn't find anything on docs, is there any way or best practice to replicate the code below?
[Petite Vue - Directive Validate Form and Inputs](https://codepen.io/JaronWanderley/pen/Yzvzjvd?editors=1100)

**Comment by Funlang** [comment]
Hi @jaronwanderley Currently Z-Data does'nt support custom directives. You could use the code like below:
```html
        <input type="text" ::value="data.name" v-rules="rulesDirective({el: this, get: () =>[
           val => !!val || 'Name is required!',
           val => val.length > 5 || 'The field need 5 or more characters',
         ]})" placeholder="Your full name" class="bg-gray-1 border-1 border-gray-3 placeholder-gray-3 p-2 rounded-lg">

```

**Comment by jaronwanderley** [comment]
Hi @Funlang I will try the workaround, do you plan implement some "plugin system", because that's will improve the framework with a ecosystem. But thanks, I'm closing the issue.

**Comment by Funlang** [comment]
Thanks for your suggestion. Yes, of course we will add custom directives support. It will take a few days. I am thinking about the syntax about it.

How about it like this?
```
  <div z-data-rules="..."
```
And it will be translated to
```
  <div :_0="rules({el: this, get: () => ...})"
```

**Comment by Funlang** [comment]
Or?
```
  <div z-d-rules="..."
```

**Comment by jaronwanderley** [comment]
> Or?
> ```
>   <div z-d-rules="..."
> ```

I always prefer write less 😎👍

**Comment by Funlang** [comment]
Hi @jaronwanderley Custom Directive is supported after Z-Data v1.9.4, please refer to https://github.com/Funlang/z-data/blob/main/README-en.md#363-custom-directive

**Comment by jaronwanderley** [comment]
Thanks again @Funlang I'm closing the issue now!
