### ISSUE TITLE
Bug with Custom Directive

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#6]
Hi @Funlang I'm here again, I was porting another directive to Z-data, but I coudn't make it work apropriately.
I was working with the [autoAnimate from FormKit](https://auto-animate.formkit.com/), and I maded a directive to use it with Petite Vue and now I'm trying to port to Z-data. My proposite is making a considerable list of directives, that can be used easily with Z-data.

Hi @Funlang I'm here again, I was porting another directive to Z-data, but I couldn't get it to work properly.
I was working with [autoAnimate from FormKit](https://auto-animate.formkit.com/), and I made a directive to use it with Petite Vue and now I'm trying to port to Z-data. My proposal is to make a considerable list of directives, which can be used easily with Z-data.

As usual, I created a comparison code:
[Petite Vue - Autoanimate Directive](https://codepen.io/JaronWanderley/pen/zYaBMwm)
[Z-Data - Autoanimate Directive](https://codepen.io/JaronWanderley/pen/gOKMBQV)

Can you help me with that?

**Comment by Funlang** [comment]
Hi @jaronwanderley Please take a look at the code https://codepen.io/funlang/pen/GRGqVpm?editors=1000

key of template for is
```
key=xxx
```
not :key=...

Z-data is keyed, so I changed it to key=v (for array, k: v, the k is "0", "1", ... and the v is the array element)

Drag and drop is not changed to fit the modification.

**Comment by Funlang** [comment]
Hi @jaronwanderley Drag and drop is working now https://codepen.io/funlang/pen/GRGqVpm?editors=1000

- use i instead of k when draging event fired

**Comment by jaronwanderley** [comment]
@Funlang sorry man!
 I'm now feeling stupid.
 Sorry about my bug... 
 Thanks again man!

**Comment by jaronwanderley** [comment]
I'm closing the issue now
