### ISSUE TITLE
Feature Request: A way to run something on start of Custom directive

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#7]
Hi @Funlang continuing my saga of custom directives, I was thinking in a way to run some code before apply the directive. For example adding a child to the node before use of directive.

My suggestion, the function to use in custom directive, do something on start and then return the function to use in the directive. Something like: 

```javascript
rulesOfValidate(({
  e: el,
  v: val, 
  m: modifiers
}) {

  // do something
  
  return (({
    e: el,
    v: val,
    m: modifiers
  }) => {
     // actual directive function
  }
}
```

What do you think?

**Comment by Funlang** [comment]
Hi @jaronwanderley It is easy, but I don't know Why. The code like below will work same as your plan.
```js
rulesOfValidate(({
  e: el,
  v: val, 
  m: modifiers
}) {

  // do something
  
  return (() => {
     // actual directive function
  })()
}
```

**Comment by Funlang** [comment]
A real example will active my imagenation.

**Comment by Funlang** [comment]
Take a look at https://codepen.io/funlang/pen/GRGqVpm?editors=1000

**Comment by Funlang** [comment]
```js
  const autoanimate = ({
    e: el,
    v: config,
  }) => {
    debugger
    return () => {
      debugger
      if (!config) {
        el.autoAnimate = autoAnimate(el)
        return
      }
      const {
        disabled,
        ...rest
      } = config
      if (disabled) {
        el.autoAnimate?.disable()
        return
      }
      el.autoAnimate = autoAnimate(el, config)
    }
  }
```

**Comment by jaronwanderley** [comment]
I'll create an example to demonstrate what I'm wanting!

**Comment by Funlang** [comment]
v1.9.6 supported https://codepen.io/funlang/pen/GRGqVpm?editors=1000

**Comment by Funlang** [comment]
@jaronwanderley I noticed your examples were using unocss.  z-data.min.all.js supports the features simular to unocss, as below:

# Rules

## 1. padding/margin
p0, m.1, pl2, mt3px, px4%

## 2. max/min - height/width
h1, w2, xh100%, nw4%

## 3. left/top/right/bottom
l0, t1, r2pt, b3px

## 4. opacity/order/z-index
op.1, ord2, z3

## 5. position ...
### position/display/cursor/visibility/white-space/user-select/pointer-events
pos-absolute, d-block, cs-pointer, v-visible, ws-nowrap, us-none, pe-all

## 6. overflow
o-scroll, ox-visible, oy-hidden

## 7. content/color/background
content-x, c#000, b#fff

## 8. media
### sm|s / md|m / lg|l / xl/2xl/xxl/print
s:p0

## 9. state
### hover|focus[-...]|active|after|before|(first|last)(-...)
hover=b#ff0, m:focus=c#f50, not-active=m0, l:after="content-x cs-move"
out-not-hover=c#000, parent^active=b#000, elder~hover=b#fff, prev+hover=c#fff

## X. group
### border, border-left, border-top, border-right, border-bottom, background, animation, align, ...
### bd|bl|bt|br|bb|bg|a|al|font|flex|grid|mask
bd="style: bold; width: 1px; color: red"

**Comment by jaronwanderley** [comment]
wooow 😮😲🤩, I didn't know about it.
Thanks for the support and the explanation man.

I'm sorry for disappearing, I lost my job at the end of the year, and today I passed on a interview.

so, I'll be closing this issue, since it is already supported right now. thanks again man!

**Comment by Funlang** [comment]
Congratulations, for your new job!
Please feel free to contact me if you have any question or problem.

**Comment by jaronwanderley** [comment]
> Congratulations, for your new job! Please feel free to contact me if you have any question or problem.

Thanks man, It's really nice to talk with you! I hope to contribute more with the Z-data Framework, I'm really excited on using it.
