### ISSUE TITLE
Is there a way of run some function on `mount` of the `z-data`?

### ISSUE THREAD

**Issue by jaronwanderley** [Funlang/z-data#9]
I was trying to run some code on first time of the z-data is applied to the tag. Can I do that?

**Comment by Funlang** [comment]
https://github.com/Funlang/z-data/blob/main/README-en.md#32-scope
```html
<tag z-data=... init=...></tag>
```
The init prop can do this.

**Comment by jaronwanderley** [comment]
Thanks man, thats works! I'm closing the issue!
